# Generated by Django 3.1.3 on 2021-06-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210604_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='trans_id',
            new_name='transaction_id',
        ),
    ]
